openapi: "3.1.0"
info:
  title: "Codosseum Challenges Service"
  description: "Service used to index and validate challenges."
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
    description: "Default Server"
    variables: {}
paths:
  /challenges/random:
    get:
      description: "Get a random challenge"
      parameters:
        - name: "difficultyFilters"
          in: "query"
          description: "Filter for challenge difficulties. A list of difficulties to _include_ in the search. If empty, all difficulties will be included."
          required: false
          allowReserved: false
          schema:
            type: "array"
            items:
              $ref: "#/components/schemas/Difficulty"
        - name: "tagFilters"
          in: "query"
          description: "Filter for challenge tags. A list of tags to _include_ in the search. If empty, all tags will be included."
          required: false
          allowReserved: false
          schema:
            type: "array"
            items:
              type: "string"
      responses:
        "200":
          description: "A random challenge meeting the filter criteria."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Info"
        "404":
          description: "No challenges found with the given filters."
          content:
            text/plain:
              schema:
                type: "string"
  /events:
    get:
      summary: "Subscribe to server-sent events"
      description: "Subscribe to server-sent events."
      responses:
        "200":
          description: "Events successfully subscribed to server-sent events."
          content:
            text/event-stream:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/TestCompleteEvent"
                  - $ref: "#/components/schemas/Event"
  /validate/{title}:
    get:
      summary: "Validate a challenge"
      description: "Validate a challenge by title."
      parameters:
        - name: "title"
          in: "path"
          description: "The title of the challenge to validate."
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "Validate successful"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationResult"
        "404":
          description: "Challenge with the given title was not found."
          content:
            application/json:
              schema:
                type: "string"
components:
  schemas:
    AbsoluteLocation:
      type: "object"
      properties:
        uri:
          $ref: "#/components/schemas/Uri"
        path:
          $ref: "#/components/schemas/JsonPointer"
      required:
        - "uri"
        - "path"
    Author:
      type: "object"
      properties:
        name:
          type: "string"
        contact:
          type: "array"
          items:
            $ref: "#/components/schemas/Contact"
      required:
        - "name"
        - "contact"
    ChallengeSchemaValidationOutput:
      type: "object"
      properties:
        success:
          type: "boolean"
        errors:
          type: "array"
          items:
            $ref: "#/components/schemas/ValidationError"
      required:
        - "success"
        - "errors"
    Contact:
      type: "object"
      properties:
        type:
          type: "string"
        contact:
          type: "string"
      required:
        - "type"
        - "contact"
    Difficulty:
      type: "string"
      enum:
        - "EASY"
        - "MEDIUM"
        - "HARD"
    Event:
      type: "object"
      examples: []
    Example:
      type: "object"
      properties:
        in:
          type: "array"
          items:
            type: "string"
        out:
          type: "array"
          items:
            type: "string"
      required:
        - "in"
        - "out"
    FailedTest:
      type: "object"
      properties:
        testName:
          type: "string"
        expectedOutput:
          type: "string"
        actualOutput:
          type: "string"
        stderr:
          type: "string"
      required:
        - "testName"
        - "expectedOutput"
        - "actualOutput"
    Info:
      type: "object"
      properties:
        $schema:
          type: "string"
        author:
          $ref: "#/components/schemas/Author"
        license:
          type: "string"
        language:
          type: "string"
        title:
          type: "string"
        difficulty:
          $ref: "#/components/schemas/Difficulty"
        tags:
          type: "array"
          items:
            type: "string"
        text:
          type: "string"
        inputFormat:
          type: "string"
        examples:
          type: "array"
          items:
            $ref: "#/components/schemas/Example"
        publicTests:
          type: "array"
          items:
            $ref: "#/components/schemas/Test"
        solution:
          $ref: "#/components/schemas/Solution"
      required:
        - "$schema"
        - "author"
        - "license"
        - "language"
        - "title"
        - "difficulty"
        - "tags"
        - "text"
        - "inputFormat"
        - "examples"
        - "publicTests"
        - "solution"
    JsonPointer:
      type: "object"
    Solution:
      type: "object"
      properties:
        language:
          type: "string"
        file:
          type: "string"
      required:
        - "language"
        - "file"
    SolutionValidationResult:
      type: "object"
      properties:
        challengeName:
          type: "string"
        success:
          type: "boolean"
        failedTests:
          type: "array"
          items:
            $ref: "#/components/schemas/FailedTest"
      required:
        - "challengeName"
        - "success"
        - "failedTests"
    TemplateValidationResult:
      type: "object"
      properties:
        success:
          type: "boolean"
        errors:
          type:
            - "string"
            - "null"
      required:
        - "success"
        - "errors"
    Test:
      type: "object"
      properties:
        name:
          type: "string"
        in:
          type: "array"
          items:
            type: "string"
        out:
          type: "array"
          items:
            type: "string"
      required:
        - "name"
        - "in"
        - "out"
    TestCompleteEvent:
      type: "object"
      properties:
        challengeName:
          type: "string"
        testName:
          type: "string"
        success:
          type: "boolean"
        failedTest:
          oneOf:
            - $ref: "#/components/schemas/FailedTest"
            - type: "null"
      required:
        - "challengeName"
        - "testName"
        - "success"
        - "failedTest"
    Uri:
      type: "object"
    ValidationError:
      type: "object"
      properties:
        schemaPath:
          $ref: "#/components/schemas/JsonPointer"
        objectPath:
          $ref: "#/components/schemas/JsonPointer"
        message:
          type: "string"
        details:
          type: "object"
          additionalProperties:
            type: "string"
        absoluteLocation:
          oneOf:
            - $ref: "#/components/schemas/AbsoluteLocation"
            - type: "null"
      required:
        - "schemaPath"
        - "objectPath"
        - "message"
    ValidationResult:
      type: "object"
      properties:
        challengeName:
          type: "string"
        schemaValidation:
          $ref: "#/components/schemas/ChallengeSchemaValidationOutput"
        solutionValidation:
          $ref: "#/components/schemas/SolutionValidationResult"
        templateValidation:
          $ref: "#/components/schemas/TemplateValidationResult"
      required:
        - "challengeName"
        - "schemaValidation"
        - "solutionValidation"
        - "templateValidation"
